# Merge Template for clash verge
# The `Merge` format used to enhance profile

proxy-groups:
  - name: é»˜è®¤
    type: select
    proxies:
      - DIRECT
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
  - name: DNS
    type: select
    proxies:
      - DIRECT
      - è‡ªåŠ¨é€‰æ‹©
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
  - name: ğŸ•¹ï¸ Game
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ Apple
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
  - name: âœˆï¸ Telegram
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ’» Microsoft
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
  - name: ğŸ¤– Google
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ“º BiliBili
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - å…¶å®ƒåœ°åŒº
      - DIRECT
  - name: âš¡ ä¸‹è½½
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
  - name: ğŸš« å¹¿å‘Šå‡€åŒ–
    type: select
    proxies:
      - PASS
      - REJECT
  - name: ğŸ“° å›½å†…ç½‘ç«™
    type: select
    proxies:
      - DIRECT
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - é»˜è®¤
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - å…¨éƒ¨èŠ‚ç‚¹
      - è‡ªåŠ¨é€‰æ‹©
      - DIRECT
  - name: é¦™æ¸¯
    type: select
    proxies:
      - REJECT
  - name: å°æ¹¾
    type: select
    proxies:
      - REJECT
  - name: æ—¥æœ¬
    type: select
    proxies:
      - REJECT
  - name: ç¾å›½
    type: select
    proxies:
      - REJECT
  - name: æ–°åŠ å¡
    type: select
    proxies:
      - REJECT
  - name: å…¶å®ƒåœ°åŒº
    type: select
    proxies:
      - REJECT
  - name: å…¨éƒ¨èŠ‚ç‚¹
    type: select
    proxies:
      - REJECT
  - name: è‡ªåŠ¨é€‰æ‹©
    type: url-test
    tolerance: 2
    proxies:
      - REJECT

rules:
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,category-ads-all,ğŸš« å¹¿å‘Šå‡€åŒ–
  - GEOSITE,category-games@cn,âš¡ ä¸‹è½½
  - GEOSITE,category-games,ğŸ•¹ï¸ Game
  - RULE-SET,Download,âš¡ ä¸‹è½½
  - GEOSITE,tracker,âš¡ ä¸‹è½½

  - GEOSITE,apple,ğŸ Apple
  - GEOSITE,telegram,âœˆï¸ Telegram
  - GEOSITE,github,ğŸ’» Microsoft
  - GEOSITE,microsoft,ğŸ’» Microsoft
  - GEOSITE,youtube,ğŸ¤– Google
  - GEOSITE,google,ğŸ¤– Google
  - GEOSITE,bilibili,ğŸ“º BiliBili
  - GEOSITE,bahamut,å°æ¹¾
  - GEOSITE,geolocation-!cn,ğŸŸ æ¼ç½‘ä¹‹é±¼

  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,google,ğŸ¤– Google
  - GEOIP,telegram,âœˆï¸ Telegram

  - GEOSITE,CN,ğŸ“° å›½å†…ç½‘ç«™
  - GEOIP,CN,ğŸ“° å›½å†…ç½‘ç«™
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼ # è§„åˆ™ä¹‹å¤–çš„

rule-providers:

  Download:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Download/Download.yaml"
    path: ./ruleset/Download.yaml
    interval: 86400
